services:
  skynest-db:
    image: mysql:latest
    container_name: skynest-db
    ports:
      - $DB_PORT_HOST:$DB_PORT_CONTAINER
    restart: unless-stopped
    env_file:
      - ./db.env
    volumes:
      - ./.db_data/mysql:/var/lib/mysql
    command: --log_bin_trust_function_creators=1
    healthcheck:
      test: mysql ${DB_NAME} --user=${DB_USERNAME} --password=${DB_PASSWORD} --silent --execute "SELECT 1;"
      interval: 15s
      timeout: 10s
      retries: 15

  skynest-token-db:
    image: cassandra:latest
    container_name: skynest-token-db
    ports:
      - $TOKEN_DB_PORT_HOST:$TOKEN_DB_PORT_CONTAINER
    restart: unless-stopped
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
    volumes:
      - ./.db_data/cassandra:/var/lib/cassandra
      - ./backend/src/main/resources/cassandra_init_keyspace.cql:/schema.cql
    healthcheck:
      test: cqlsh --username=${TOKEN_DB_USERNAME} --password={TOKEN_DB_PASSWORD} --file=/schema.cql
      interval: 15s
      timeout: 10s
      retries: 15

  skynest-file-db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - $FILE_DB_PORT_HOST:$FILE_DB_PORT_CONTAINER
    env_file:
      - ./file_db.env
    volumes:
      - ./.db_data/mongo:/data/db

  skynest-be:
    depends_on:
      skynest-db:
        condition: service_healthy
      skynest-token-db:
        condition: service_healthy
    image: skynest/skynest-api
    container_name: skynest-be
    ports:
      - $SPRING_PORT_HOST:$SPRING_PORT_CONTAINER
    restart: on-failure
    build: ./backend
    env_file:
      - ./spring.env
    volumes:
      - ./.m2:/root/.m2
    stdin_open: true
    tty: true
