services:

  skynest-db:
    image: mysql:latest
    container_name: skynest-db
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'skynest'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'

  skynest-token-db:
    image: cassandra:latest
    container_name: skynest-token-db
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: unless-stopped
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  skynest-token-db-init:
    container_name: skynest-token-db-init
    image: cassandra:latest
    depends_on:
      skynest-token-db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/cassandra_init_keyspace.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

volumes:
  db: